language: java

jdk:
  - oraclejdk8
  
# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'
  
before_install:
- export CURRENT_DIR=`pwd`
- rm -rf /tmp/ibole-infrastructure-master
- wget -O /tmp/ibole-infrastructure.zip https://github.com/benson-git/ibole-infrastructure/archive/master.zip
- cd /tmp
- unzip ibole-infrastructure.zip
- cd ibole-infrastructure-master
- mvn clean install -Dmaven.test.skip=true
- cd $CURRENT_DIR

after_success:
  - mvn clean -DCOVERALLS_TOKEN=$COVERALLS_TOKEN test jacoco:report coveralls:report
